apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-rest
  namespace: tr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-rest
  template:
    metadata:
      labels:
        app: test-rest
    spec:
      containers:
      - name: test-rest
        image: apascualco/kgorest:19 
        ports:
        - containerPort: 80
